const BankList = [
  { id: 2, display: "NO COBRO POR BANCO" },
  { id: 7, display: "BANCO DE GALICIA Y BUENOS AIRES S.A.U." },
  { id: 11, display: "BANCO DE LA NACION ARGENTINA" },
  { id: 14, display: "BANCO DE LA PROVINCIA DE BUENOS AIRES" },
  { id: 15, display: "INDUSTRIAL AND COMMERCIAL BANK OF CHINA" },
  { id: 16, display: "CITIBANK N.A." },
  { id: 17, display: "BANCO BBVA ARGENTINA S.A." },
  { id: 20, display: "BANCO DE LA PROVINCIA DE CORDOBA S.A." },
  { id: 27, display: "BANCO SUPERVIELLE S.A." },
  { id: 29, display: "BANCO DE LA CIUDAD DE BUENOS AIRES" },
  { id: 34, display: "BANCO PATAGONIA S.A." },
  { id: 44, display: "BANCO HIPOTECARIO S.A." },
  { id: 45, display: "BANCO DE SAN JUAN S.A." },
  { id: 65, display: "BANCO MUNICIPAL DE ROSARIO" },
  { id: 72, display: "BANCO SANTANDER ARGENTINA S.A." },
  { id: 83, display: "BANCO DEL CHUBUT S.A." },
  { id: 86, display: "BANCO DE SANTA CRUZ S.A." },
  { id: 93, display: "BANCO DE LA PAMPA SOCIEDAD DE ECONOMÍA M" },
  { id: 94, display: "BANCO DE CORRIENTES S.A." },
  { id: 97, display: "BANCO PROVINCIA DEL NEUQUÉN SOCIEDAD ANÓ" },
  { id: 131, display: "BANK OF CHINA LIMITED SUCURSAL BUENOS AI" },
  { id: 143, display: "BRUBANK S.A.U." },
  { id: 147, display: "BIBANK S.A." },
  { id: 150, display: "HSBC BANK ARGENTINA S.A." },
  { id: 158, display: "OPEN BANK ARGENTINA S.A." },
  { id: 165, display: "JPMORGAN CHASE BANK, NATIONAL ASSOCIATIO" },
  { id: 191, display: "BANCO CREDICOOP COOPERATIVO LIMITADO" },
  { id: 198, display: "BANCO DE VALORES S.A." },
  { id: 247, display: "BANCO ROELA S.A." },
  { id: 254, display: "BANCO MARIVA S.A." },
  { id: 259, display: "BANCO BMA S.A.U." },
  { id: 266, display: "BNP PARIBAS" },
  { id: 268, display: "BANCO PROVINCIA DE TIERRA DEL FUEGO" },
  { id: 269, display: "BANCO DE LA REPUBLICA ORIENTAL DEL URUGU" },
  { id: 277, display: "BANCO SAENZ S.A." },
  { id: 281, display: "BANCO MERIDIAN S.A." },
  { id: 285, display: "BANCO MACRO S.A." },
  { id: 299, display: "BANCO COMAFI SOCIEDAD ANONIMA" },
  { id: 300, display: "BANCO DE INVERSION Y COMERCIO EXTERIOR S" },
  { id: 301, display: "BANCO PIANO S.A." },
  { id: 305, display: "BANCO JULIO SOCIEDAD ANONIMA" },
  { id: 309, display: "BANCO RIOJA SOCIEDAD ANONIMA UNIPERSONAL" },
  { id: 310, display: "BANCO DEL SOL S.A." },
  { id: 311, display: "NUEVO BANCO DEL CHACO S. A." },
  { id: 312, display: "BANCO VOII S.A." },
  { id: 315, display: "BANCO DE FORMOSA S.A." },
  { id: 319, display: "BANCO CMF S.A." },
  { id: 321, display: "BANCO DE SANTIAGO DEL ESTERO S.A." },
  { id: 322, display: "BANCO INDUSTRIAL S.A." },
  { id: 330, display: "NUEVO BANCO DE SANTA FE SOCIEDAD ANONIMA" },
  { id: 331, display: "BANCO CETELEM ARGENTINA S.A." },
  { id: 332, display: "BANCO DE SERVICIOS FINANCIEROS S.A." },
  { id: 338, display: "BANCO DE SERVICIOS Y TRANSACCIONES S.A." },
  { id: 339, display: "RCI BANQUE S.A." },
  { id: 340, display: "BACS BANCO DE CREDITO Y SECURITIZACION S" },
  { id: 341, display: "BANCO MASVENTAS S.A." },
  { id: 384, display: "WILOBANK S.A.U." },
  { id: 386, display: "NUEVO BANCO DE ENTRE RÍOS S.A." },
  { id: 389, display: "BANCO COLUMBIA S.A." },
  { id: 426, display: "BANCO BICA S.A." },
  { id: 431, display: "BANCO COINAG S.A." },
  { id: 432, display: "BANCO DE COMERCIO S.A." },
  { id: 435, display: "BANCO SUCREDITO REGIONAL S.A.U." },
  { id: 448, display: "BANCO DINO S.A." },
  { id: 44077, display: "COMPAÑIA FINANCIERA ARGENTINA S.A." },
  { id: 44088, display: "VOLKSWAGEN FINANCIAL SERVICES COMPAÑIA F" },
  { id: 44090, display: "IUDU COMPAÑÍA FINANCIERA S.A." },
  { id: 44092,display: "FCA COMPAÑIA FINANCIERA S.A.",},
  { id: 44093, display: "GPAT COMPAÑIA FINANCIERA S.A.U." },
  { id: 44094, display: "MERCEDES-BENZ COMPAÑÍA FINANCIERA ARGENT" },
  { id: 44095, display: "ROMBO COMPAÑÍA FINANCIERA S.A." },
  { id: 44096, display: "JOHN DEERE CREDIT COMPAÑÍA FINANCIERA S." },
  { id: 44098, display: "PSA FINANCE ARGENTINA COMPAÑÍA FINANCIER" },
  { id: 44099, display: "TOYOTA COMPAÑÍA FINANCIERA DE ARGENTINA" },
  { id: 45030, display: "NARANJA DIGITAL COMPAÑÍA FINANCIERA S.A." },
  { id: 45056, display: "MONTEMAR COMPAÑIA FINANCIERA S.A." },
  { id: 45072, display: "REBA COMPAÑIA FINANCIERA S.A." },
  { id: 65203, display: "CREDITO REGIONAL COMPAÑIA FINANCIERA S.A." },
];
export default BankList;
